// ============================================
// GOLD SENTIMENT MODEL — Data Layer
// Replace with your own historical data
// ============================================

// --- Gold Price Data (Weekly candles, simplified OHLC) ---
// Format: { time: 'YYYY-MM-DD', open, high, low, close }
const GOLD_DATA = generateGoldData();

function generateGoldData() {
    const data = [];
    const baseData = [
        // 2000-2002: Post dot-com, gold bottoming ~$270-$320
        { start: '2000-01-03', months: 12, startPrice: 283, endPrice: 272, volatility: 8 },
        { start: '2001-01-01', months: 12, startPrice: 272, endPrice: 278, volatility: 10 },
        { start: '2002-01-01', months: 12, startPrice: 278, endPrice: 348, volatility: 12 },
        // 2003-2007: Bull run
        { start: '2003-01-01', months: 12, startPrice: 348, endPrice: 416, volatility: 15 },
        { start: '2004-01-01', months: 12, startPrice: 416, endPrice: 438, volatility: 14 },
        { start: '2005-01-01', months: 12, startPrice: 438, endPrice: 517, volatility: 18 },
        { start: '2006-01-01', months: 12, startPrice: 517, endPrice: 636, volatility: 25 },
        { start: '2007-01-01', months: 12, startPrice: 636, endPrice: 836, volatility: 30 },
        // 2008-2011: Financial crisis & peak
        { start: '2008-01-01', months: 12, startPrice: 836, endPrice: 882, volatility: 60 },
        { start: '2009-01-01', months: 12, startPrice: 882, endPrice: 1096, volatility: 40 },
        { start: '2010-01-01', months: 12, startPrice: 1096, endPrice: 1421, volatility: 35 },
        { start: '2011-01-01', months: 12, startPrice: 1421, endPrice: 1566, volatility: 55 },
        // 2012-2015: Correction
        { start: '2012-01-01', months: 12, startPrice: 1566, endPrice: 1675, volatility: 40 },
        { start: '2013-01-01', months: 12, startPrice: 1675, endPrice: 1205, volatility: 50 },
        { start: '2014-01-01', months: 12, startPrice: 1205, endPrice: 1184, volatility: 30 },
        { start: '2015-01-01', months: 12, startPrice: 1184, endPrice: 1062, volatility: 25 },
        // 2016-2019: Recovery
        { start: '2016-01-01', months: 12, startPrice: 1062, endPrice: 1151, volatility: 30 },
        { start: '2017-01-01', months: 12, startPrice: 1151, endPrice: 1303, volatility: 25 },
        { start: '2018-01-01', months: 12, startPrice: 1303, endPrice: 1282, volatility: 30 },
        { start: '2019-01-01', months: 12, startPrice: 1282, endPrice: 1523, volatility: 35 },
        // 2020-2026: COVID & new highs
        { start: '2020-01-01', months: 12, startPrice: 1523, endPrice: 1898, volatility: 60 },
        { start: '2021-01-01', months: 12, startPrice: 1898, endPrice: 1829, volatility: 40 },
        { start: '2022-01-01', months: 12, startPrice: 1829, endPrice: 1824, volatility: 50 },
        { start: '2023-01-01', months: 12, startPrice: 1824, endPrice: 2063, volatility: 45 },
        { start: '2024-01-01', months: 12, startPrice: 2063, endPrice: 2650, volatility: 55 },
        // 2025: Gold breaks $3,000 on tariffs, CB buying, fiscal fears
        { start: '2025-01-01', months: 6, startPrice: 2650, endPrice: 3100, volatility: 65 },
        { start: '2025-07-01', months: 6, startPrice: 3100, endPrice: 3350, volatility: 70 },
        // 2026: Continued strength — trade war escalation, dollar erosion
        { start: '2026-01-01', months: 3, startPrice: 3350, endPrice: 3520, volatility: 65 },
    ];

    for (const segment of baseData) {
        const startDate = new Date(segment.start);
        const weeks = Math.round(segment.months * 4.33);
        const priceStep = (segment.endPrice - segment.startPrice) / weeks;

        for (let i = 0; i < weeks; i++) {
            const date = new Date(startDate);
            date.setDate(date.getDate() + i * 7);
            const dateStr = date.toISOString().split('T')[0];

            const basePrice = segment.startPrice + priceStep * i;
            const noise = () => (Math.random() - 0.5) * segment.volatility;
            const open = basePrice + noise() * 0.3;
            const close = basePrice + priceStep + noise() * 0.3;
            const high = Math.max(open, close) + Math.abs(noise()) * 0.5;
            const low = Math.min(open, close) - Math.abs(noise()) * 0.5;

            data.push({
                time: dateStr,
                open: Math.round(open * 100) / 100,
                high: Math.round(high * 100) / 100,
                low: Math.round(low * 100) / 100,
                close: Math.round(close * 100) / 100,
            });
        }
    }

    // Remove duplicates by date
    const seen = new Set();
    return data.filter(d => {
        if (seen.has(d.time)) return false;
        seen.add(d.time);
        return true;
    }).sort((a, b) => a.time.localeCompare(b.time));
}


// --- Presidential Term Periods (for chart overlays) ---
const PRESIDENTIAL_PERIODS = [
    { name: 'Clinton', party: 'democrat', start: '1993-01-20', end: '2001-01-20' },
    { name: 'Bush', party: 'republican', start: '2001-01-20', end: '2009-01-20' },
    { name: 'Obama', party: 'democrat', start: '2009-01-20', end: '2017-01-20' },
    { name: 'Trump 1st', party: 'republican', start: '2017-01-20', end: '2021-01-20' },
    { name: 'Biden', party: 'democrat', start: '2021-01-20', end: '2025-01-20' },
    { name: 'Trump 2nd', party: 'republican', start: '2025-01-20', end: '2029-01-20' },
];

// --- Crisis Periods (color-coded zones on chart) ---
const CRISIS_PERIODS = [
    {
        id: 'dotcom',
        name: 'Dot-Com Crash',
        type: 'financial',
        color: 'rgba(248, 113, 113, 0.06)',
        borderColor: 'rgba(248, 113, 113, 0.25)',
        start: '2000-03-10',
        end: '2002-10-09',
        goldImpact: 'Initially flat, then began structural bull run as Fed slashed rates',
        label: 'DOT-COM',
    },
    {
        id: '911-afghan',
        name: '9/11 & Afghanistan War',
        type: 'geopolitical',
        color: 'rgba(139, 92, 246, 0.06)',
        borderColor: 'rgba(139, 92, 246, 0.25)',
        start: '2001-09-11',
        end: '2002-03-01',
        goldImpact: 'Safe-haven surge +7.7%, then sustained geopolitical bid',
        label: '9/11',
    },
    {
        id: 'iraq',
        name: 'Iraq War',
        type: 'geopolitical',
        color: 'rgba(139, 92, 246, 0.06)',
        borderColor: 'rgba(139, 92, 246, 0.25)',
        start: '2003-03-20',
        end: '2003-12-13',
        goldImpact: 'War premium drove gold +15%, dollar weakened on twin deficits',
        label: 'IRAQ WAR',
    },
    {
        id: 'gfc',
        name: 'Global Financial Crisis',
        type: 'financial',
        color: 'rgba(248, 113, 113, 0.08)',
        borderColor: 'rgba(248, 113, 113, 0.3)',
        start: '2007-12-01',
        end: '2009-06-01',
        goldImpact: 'Liquidity crash then massive rally — Bear Stearns to QE1. Net +40%',
        label: 'GFC',
    },
    {
        id: 'eu-debt',
        name: 'European Sovereign Debt Crisis',
        type: 'financial',
        color: 'rgba(248, 113, 113, 0.06)',
        borderColor: 'rgba(248, 113, 113, 0.25)',
        start: '2010-04-01',
        end: '2012-06-01',
        goldImpact: 'Gold surged to ATH $1,921 as EU fragmentation fears peaked',
        label: 'EU DEBT CRISIS',
    },
    {
        id: 'taper',
        name: 'Taper Tantrum & Gold Crash',
        type: 'monetary',
        color: 'rgba(96, 165, 250, 0.06)',
        borderColor: 'rgba(96, 165, 250, 0.25)',
        start: '2013-04-01',
        end: '2013-12-31',
        goldImpact: 'Worst year since 1981 — gold fell 28% on rising real rates & taper fears',
        label: 'TAPER TANTRUM',
    },
    {
        id: 'covid',
        name: 'COVID-19 Pandemic',
        type: 'pandemic',
        color: 'rgba(251, 146, 60, 0.06)',
        borderColor: 'rgba(251, 146, 60, 0.25)',
        start: '2020-02-20',
        end: '2020-12-31',
        goldImpact: 'Liquidity crash then new ATH $2,075 on unlimited QE & zero rates',
        label: 'COVID-19',
    },
    {
        id: 'inflation-crisis',
        name: 'Inflation Spike & Fed Tightening',
        type: 'monetary',
        color: 'rgba(96, 165, 250, 0.06)',
        borderColor: 'rgba(96, 165, 250, 0.25)',
        start: '2022-03-16',
        end: '2023-07-26',
        goldImpact: 'Gold pressured by 20-year dollar high & soaring real rates. -14.6% trough',
        label: 'FED TIGHTENING',
    },
    {
        id: 'trade-war-2025',
        name: 'Trade War Escalation',
        type: 'trade',
        color: 'rgba(234, 179, 8, 0.06)',
        borderColor: 'rgba(234, 179, 8, 0.25)',
        start: '2025-02-01',
        end: '2025-08-01',
        goldImpact: 'Liberation Day tariffs drove gold past $3,000 on stagflation fears',
        label: 'TRADE WAR',
    },
    {
        id: 'fiscal-crisis',
        name: 'US Fiscal / Debt Ceiling Crisis',
        type: 'fiscal',
        color: 'rgba(248, 113, 113, 0.06)',
        borderColor: 'rgba(248, 113, 113, 0.25)',
        start: '2025-09-01',
        end: '2025-12-31',
        goldImpact: 'Fiscal credibility erosion pushed gold to $3,350 as CB diversification accelerated',
        label: 'DEBT CRISIS',
    },
];

// Crisis type legend
const CRISIS_TYPES = {
    financial:   { label: 'Financial Crisis',    color: '#f87171' },
    geopolitical:{ label: 'Geopolitical Crisis',  color: '#8b5cf6' },
    pandemic:    { label: 'Pandemic',             color: '#fb923c' },
    monetary:    { label: 'Monetary Policy Shock', color: '#60a5fa' },
    trade:       { label: 'Trade War',            color: '#eab308' },
    fiscal:      { label: 'Fiscal Crisis',        color: '#f87171' },
};


// --- Correlated Instruments (Enhanced) ---
const INSTRUMENTS = {
    // POSITIVE CORRELATION
    vix: {
        name: 'VIX',
        fullName: 'CBOE Volatility Index',
        correlation: 'positive',
        corrValue: '+0.62',
        currentValue: '24.68',
        trend: 'up',
        trendLabel: 'Elevated',
        description: 'Fear gauge — spikes drive safe-haven flows into gold',
        mechanism: 'When VIX spikes, equity markets are selling off. Investors rotate into gold as a safe haven, creating a positive feedback loop. The correlation is strongest during tail-risk events (>30 VIX) and weaker in calm markets.',
        historicalSnapshots: [
            { date: 'Sep 2001', event: '9/11 Attacks', value: '43.7', goldMove: '+7.7%' },
            { date: 'Oct 2008', event: 'Lehman Collapse', value: '80.9', goldMove: '-13.5% (liquidity)' },
            { date: 'Mar 2020', event: 'COVID Crash', value: '82.7', goldMove: '-12% then +40%' },
            { date: 'Apr 2025', event: 'Liberation Day', value: '42.1', goldMove: '+4.9%' },
        ],
        ranges: { low: '< 15 (complacent)', mid: '15-25 (normal)', high: '25-40 (fear)', extreme: '> 40 (panic)' },
    },
    cpi: {
        name: 'CPI',
        fullName: 'Consumer Price Index (YoY %)',
        correlation: 'positive',
        corrValue: '+0.71',
        currentValue: '3.4%',
        trend: 'flat',
        trendLabel: 'Sticky',
        description: 'Inflation erodes fiat purchasing power, boosting gold demand',
        mechanism: 'Gold is a classic inflation hedge. When CPI rises, the real value of cash deteriorates, making gold relatively more attractive. However, if the Fed responds aggressively (like 2022), rising real rates can overpower the inflation tailwind.',
        historicalSnapshots: [
            { date: '2011', event: 'QE-Driven', value: '3.2%', goldMove: 'ATH $1,921' },
            { date: 'Jun 2022', event: '40-Year Peak', value: '9.1%', goldMove: '-14.6% (real rates won)' },
            { date: '2023', event: 'Disinflation', value: '3.1%', goldMove: '+13.4% (CB buying)' },
            { date: '2025-26', event: 'Tariff Inflation', value: '3.4%', goldMove: '+32.8%' },
        ],
        ranges: { low: '< 2% (deflation risk)', mid: '2-3% (target)', high: '3-5% (elevated)', extreme: '> 5% (crisis)' },
    },
    unemployment: {
        name: 'UNEMPLOYMENT',
        fullName: 'US Unemployment Rate (U-3)',
        correlation: 'positive',
        corrValue: '+0.48',
        currentValue: '4.8%',
        trend: 'up',
        trendLabel: 'Rising',
        description: 'Rising unemployment signals economic weakness, favoring gold',
        mechanism: 'Weaker labor markets increase probability of Fed rate cuts and fiscal stimulus, both bullish for gold. High unemployment also signals recession risk, driving safe-haven demand. The correlation is moderate because gold sometimes rallies even with low unemployment (2023-24).',
        historicalSnapshots: [
            { date: 'Oct 2009', event: 'GFC Peak', value: '10.0%', goldMove: '+25% (yr)' },
            { date: 'Apr 2020', event: 'COVID Peak', value: '14.7%', goldMove: 'New ATH $2,075' },
            { date: 'Jan 2023', event: 'Post-Hike Low', value: '3.4%', goldMove: '+13.4% (CB buying)' },
            { date: 'Mar 2026', event: 'Rising Trend', value: '4.8%', goldMove: '+17% YTD' },
        ],
        ranges: { low: '< 4% (full employment)', mid: '4-5% (normal)', high: '5-7% (weak)', extreme: '> 7% (recession)' },
    },
    // NEGATIVE CORRELATION
    dxy: {
        name: 'DXY',
        fullName: 'US Dollar Index (Basket vs EUR, JPY, GBP, etc.)',
        correlation: 'negative',
        corrValue: '-0.82',
        currentValue: '98.45',
        trend: 'down',
        trendLabel: 'Weakening',
        description: 'Strong dollar makes gold more expensive globally, suppressing demand',
        mechanism: 'Gold is priced in USD globally. A stronger dollar makes gold more expensive for foreign buyers, reducing demand. The DXY-Gold relationship is the single strongest and most consistent correlation in the gold market — accounting for ~65% of gold\'s variance historically.',
        historicalSnapshots: [
            { date: '2002-2008', event: 'Weak Dollar Era', value: '120 → 72', goldMove: '$280 → $1,000' },
            { date: 'Sep 2022', event: '20-Year High', value: '114.8', goldMove: '$1,622 low' },
            { date: '2024', event: 'Range-Bound', value: '103-107', goldMove: '+28% (CB buying)' },
            { date: '2026', event: 'Weakening', value: '98.5', goldMove: '$4,600+' },
        ],
        ranges: { low: '< 90 (weak dollar)', mid: '90-100 (neutral)', high: '100-110 (strong)', extreme: '> 110 (very strong)' },
    },
    realRates: {
        name: 'REAL RATES',
        fullName: '10Y TIPS Yield (Real Interest Rate)',
        correlation: 'negative',
        corrValue: '-0.88',
        currentValue: '0.85%',
        trend: 'down',
        trendLabel: 'Declining',
        description: 'Higher real yields increase opportunity cost of holding gold',
        mechanism: 'Gold yields nothing. When real (inflation-adjusted) interest rates are high, investors can earn a positive real return in bonds — making gold\'s zero yield unattractive. When real rates are negative, you\'re losing purchasing power in bonds, making gold the superior store of value. This is the #1 fundamental driver of gold.',
        historicalSnapshots: [
            { date: 'Aug 2011', event: 'Deeply Negative', value: '-0.65%', goldMove: 'ATH $1,921' },
            { date: 'Aug 2020', event: 'Record Negative', value: '-1.08%', goldMove: 'ATH $2,075' },
            { date: 'Oct 2022', event: 'Rapid Rise', value: '+1.74%', goldMove: '$1,622 low' },
            { date: '2026', event: 'Declining', value: '+0.85%', goldMove: '$4,600+' },
        ],
        ranges: { low: '< 0% (negative = bullish gold)', mid: '0-1% (neutral)', high: '1-2% (headwind)', extreme: '> 2% (major headwind)' },
    },
};


// --- Significant Gold Events ---
const GOLD_EVENTS = [
    {
        id: 'dotcom-crash',
        date: '2001-09-17',
        title: '9/11 & Safe Haven Surge',
        direction: 'bullish',
        priceFrom: 272,
        priceTo: 293,
        change: '+7.7%',
        summary: 'Terror attacks triggered immediate flight to safety. Gold surged as equities collapsed and geopolitical uncertainty spiked to generational levels.',
        factors: [
            { name: 'VIX', direction: 'up', detail: 'Spiked to 43.7' },
            { name: 'DXY', direction: 'down', detail: 'Dollar weakened on uncertainty' },
            { name: 'Real Rates', direction: 'down', detail: 'Fed emergency cuts' },
            { name: 'Unemployment', direction: 'up', detail: 'Rising post-recession' },
        ],
        sentiment: 'Extreme fear and geopolitical shock created a textbook safe-haven bid. The Federal Reserve slashed rates in emergency sessions, collapsing real yields and providing a dual tailwind for gold.',
        keyDrivers: 'Geopolitical crisis, emergency rate cuts, equity market collapse',
    },
    {
        id: 'iraq-war',
        date: '2003-03-20',
        title: 'Iraq War — Geopolitical Premium',
        direction: 'bullish',
        priceFrom: 337,
        priceTo: 388,
        change: '+15.1%',
        summary: 'The invasion of Iraq injected sustained geopolitical risk premium into gold. Uncertainty about Middle East stability and US fiscal expansion supported the rally.',
        factors: [
            { name: 'VIX', direction: 'up', detail: 'Elevated ~30+' },
            { name: 'DXY', direction: 'down', detail: 'Dollar declining on twin deficits' },
            { name: 'CPI', direction: 'up', detail: 'Oil-driven inflation rising' },
            { name: 'Real Rates', direction: 'down', detail: 'Fed holding rates at 1%' },
        ],
        sentiment: 'War premium combined with structural dollar weakness from twin deficits. The Fed\'s ultra-low rate policy made gold\'s zero yield relatively attractive.',
        keyDrivers: 'War risk premium, weak dollar, accommodative Fed policy',
    },
    {
        id: 'gfc-crash',
        date: '2008-03-17',
        title: 'Bear Stearns Collapse — GFC Begins',
        direction: 'bullish',
        priceFrom: 920,
        priceTo: 1011,
        change: '+9.9%',
        summary: 'The collapse of Bear Stearns signaled the start of the Global Financial Crisis. Gold initially surged as a safe haven before a liquidity-driven selloff.',
        factors: [
            { name: 'VIX', direction: 'up', detail: 'Surged past 30' },
            { name: 'DXY', direction: 'down', detail: 'Dollar weak on rate cut expectations' },
            { name: 'Real Rates', direction: 'down', detail: 'Aggressive Fed easing' },
            { name: 'Unemployment', direction: 'up', detail: 'Rising rapidly' },
        ],
        sentiment: 'Systemic banking crisis triggered massive safe-haven flows. The Fed\'s aggressive easing crushed real yields, but a temporary liquidity squeeze caused a brief mid-crisis gold dip before the structural rally resumed.',
        keyDrivers: 'Banking crisis, real yield collapse, systemic risk',
    },
    {
        id: 'lehman',
        date: '2008-09-15',
        title: 'Lehman Brothers Bankruptcy',
        direction: 'bearish',
        priceFrom: 850,
        priceTo: 735,
        change: '-13.5%',
        summary: 'Lehman\'s collapse paradoxically caused gold to sell off as the liquidity crisis forced hedge funds and institutions to liquidate all assets, including gold, to meet margin calls.',
        factors: [
            { name: 'VIX', direction: 'up', detail: 'Exploded to 80+' },
            { name: 'DXY', direction: 'up', detail: 'Dollar surged on deleveraging' },
            { name: 'Real Rates', direction: 'down', detail: 'Yields collapsing' },
            { name: 'Unemployment', direction: 'up', detail: 'Spiking toward 10%' },
        ],
        sentiment: 'A classic liquidity crunch selloff. In extreme panic, correlations go to 1 — everything gets sold. The dollar surged as global deleveraging forced USD demand. Gold recovered within weeks as QE expectations built.',
        keyDrivers: 'Forced liquidation, margin calls, dollar squeeze',
    },
    {
        id: 'qe1',
        date: '2009-03-18',
        title: 'QE1 Announced — $1.75T',
        direction: 'bullish',
        priceFrom: 922,
        priceTo: 990,
        change: '+7.4%',
        summary: 'The Federal Reserve announced its first round of quantitative easing, purchasing $1.75 trillion in assets. This massive monetary expansion fueled gold\'s next leg higher.',
        factors: [
            { name: 'Real Rates', direction: 'down', detail: 'Deeply negative' },
            { name: 'DXY', direction: 'down', detail: 'Dollar weakened on money printing' },
            { name: 'CPI', direction: 'flat', detail: 'Deflation fears near-term' },
            { name: 'VIX', direction: 'down', detail: 'Beginning to decline from peak' },
        ],
        sentiment: 'Unprecedented monetary expansion devalued the dollar and crushed real yields into deeply negative territory. Gold became the ultimate hedge against currency debasement.',
        keyDrivers: 'Quantitative easing, dollar debasement, negative real rates',
    },
    {
        id: 'gold-peak-2011',
        date: '2011-09-06',
        title: 'All-Time High — $1,921',
        direction: 'bullish',
        priceFrom: 1650,
        priceTo: 1921,
        change: '+16.4%',
        summary: 'Gold reached its all-time high (at the time) as the European debt crisis, US debt ceiling crisis, and S&P downgrade of US credit rating created a perfect storm of safe-haven demand.',
        factors: [
            { name: 'VIX', direction: 'up', detail: 'Elevated on EU crisis fears' },
            { name: 'DXY', direction: 'down', detail: 'Dollar weak on QE2' },
            { name: 'Real Rates', direction: 'down', detail: 'Deeply negative (-1%+)' },
            { name: 'CPI', direction: 'up', detail: 'Inflation above 3%' },
            { name: 'Unemployment', direction: 'up', detail: 'Still above 9%' },
        ],
        sentiment: 'A confluence of crises: European sovereign debt crisis, US credit downgrade, ongoing QE, and elevated inflation created the perfect environment for gold. Every macro factor aligned bullishly.',
        keyDrivers: 'EU crisis, US downgrade, deeply negative real rates, QE2',
    },
    {
        id: 'gold-crash-2013',
        date: '2013-04-15',
        title: 'Flash Crash — Worst 2-Day Drop in 30 Years',
        direction: 'bearish',
        priceFrom: 1565,
        priceTo: 1321,
        change: '-15.6%',
        summary: 'Gold suffered its worst two-day decline in three decades. Triggered by Cyprus selling gold reserves and Fed taper expectations, massive stop-loss cascades amplified the selloff.',
        factors: [
            { name: 'Real Rates', direction: 'up', detail: 'Rising on taper expectations' },
            { name: 'DXY', direction: 'up', detail: 'Dollar strengthening' },
            { name: 'VIX', direction: 'down', detail: 'Low volatility environment' },
            { name: 'CPI', direction: 'down', detail: 'Inflation declining toward 1%' },
        ],
        sentiment: 'The narrative shifted from inflation fear to recovery optimism. Rising real rates removed gold\'s key tailwind. The Cyprus forced gold sale sparked panic, and algorithmic stop-losses created a cascading liquidation event.',
        keyDrivers: 'Taper tantrum expectations, rising real rates, Cyprus gold sale, technical breakdown',
    },
    {
        id: 'taper-tantrum',
        date: '2013-06-19',
        title: 'Bernanke Taper Tantrum',
        direction: 'bearish',
        priceFrom: 1380,
        priceTo: 1192,
        change: '-13.6%',
        summary: 'Fed Chair Bernanke suggested tapering QE asset purchases. Gold plunged as the market priced in the end of easy money and a normalization of real interest rates.',
        factors: [
            { name: 'Real Rates', direction: 'up', detail: '10Y TIPS yield surged +130bps' },
            { name: 'DXY', direction: 'up', detail: 'Dollar rallied sharply' },
            { name: 'VIX', direction: 'up', detail: 'Brief spike on tantrum' },
            { name: 'Unemployment', direction: 'down', detail: 'Improving to ~7.5%' },
        ],
        sentiment: 'The taper tantrum marked the definitive end of gold\'s post-GFC bull run. Rising real yields and a stronger dollar created a toxic environment for gold. The improving employment picture reduced need for accommodation.',
        keyDrivers: 'Taper announcement, real rate surge, dollar strength',
    },
    {
        id: 'trump-election',
        date: '2016-11-09',
        title: 'Trump Election — Initial Selloff',
        direction: 'bearish',
        priceFrom: 1305,
        priceTo: 1170,
        change: '-10.3%',
        summary: 'Trump\'s election initially sent gold higher overnight, but reversed sharply as markets pivoted to the "reflation trade" — expecting tax cuts, deregulation, and dollar strength.',
        factors: [
            { name: 'DXY', direction: 'up', detail: 'Dollar surged on growth expectations' },
            { name: 'Real Rates', direction: 'up', detail: 'Rising on fiscal expansion' },
            { name: 'VIX', direction: 'down', detail: 'Quick normalization' },
            { name: 'CPI', direction: 'up', detail: 'Reflation expectations building' },
        ],
        sentiment: 'The classic "sell the safe haven, buy the risk asset" rotation. Markets priced in pro-growth policies driving dollar strength and higher real rates, both headwinds for gold.',
        keyDrivers: 'Reflation trade, dollar strength, rising rate expectations',
    },
    {
        id: 'covid-crash',
        date: '2020-03-09',
        title: 'COVID-19 Pandemic Crash',
        direction: 'bearish',
        priceFrom: 1672,
        priceTo: 1471,
        change: '-12.0%',
        summary: 'Similar to Lehman, the COVID crash initially hit gold as a liquidity event. Forced selling across all asset classes as margin calls cascaded through the system.',
        factors: [
            { name: 'VIX', direction: 'up', detail: 'Spiked to 82 — highest ever' },
            { name: 'DXY', direction: 'up', detail: 'Dollar squeeze on deleveraging' },
            { name: 'Unemployment', direction: 'up', detail: 'About to explode to 14.7%' },
            { name: 'Real Rates', direction: 'down', detail: 'Collapsing on emergency cuts' },
        ],
        sentiment: 'A repeat of the Lehman playbook: extreme panic → forced liquidation → sell everything for cash. Gold recovered rapidly as the Fed launched unlimited QE and rates went to zero.',
        keyDrivers: 'Pandemic panic, liquidity crisis, forced deleveraging',
    },
    {
        id: 'gold-ath-2020',
        date: '2020-08-07',
        title: 'New All-Time High — $2,075',
        direction: 'bullish',
        priceFrom: 1810,
        priceTo: 2075,
        change: '+14.6%',
        summary: 'Gold reached a new all-time high as unlimited QE, zero rates, massive fiscal stimulus, and pandemic uncertainty combined to create the perfect storm for precious metals.',
        factors: [
            { name: 'Real Rates', direction: 'down', detail: 'Most negative in history (-1.1%)' },
            { name: 'DXY', direction: 'down', detail: 'Dollar at multi-year lows' },
            { name: 'CPI', direction: 'up', detail: 'Inflation expectations rising' },
            { name: 'VIX', direction: 'down', detail: 'Declining but elevated' },
            { name: 'Unemployment', direction: 'up', detail: 'Still above 10%' },
        ],
        sentiment: 'The most bullish macro backdrop for gold in history: deeply negative real rates, collapsing dollar, massive monetary expansion, rising inflation expectations, and ongoing pandemic uncertainty.',
        keyDrivers: 'Record negative real rates, unlimited QE, dollar weakness, fiscal stimulus',
    },
    {
        id: 'fed-hikes-2022',
        date: '2022-09-28',
        title: 'Aggressive Fed Hiking — Gold Pressured',
        direction: 'bearish',
        priceFrom: 1900,
        priceTo: 1622,
        change: '-14.6%',
        summary: 'The Fed\'s most aggressive tightening cycle in 40 years sent real rates soaring and the dollar to 20-year highs, creating maximum headwinds for gold.',
        factors: [
            { name: 'Real Rates', direction: 'up', detail: 'Surged above 1.5%' },
            { name: 'DXY', direction: 'up', detail: 'Hit 114 — 20-year high' },
            { name: 'CPI', direction: 'up', detail: '9.1% peak but declining' },
            { name: 'Unemployment', direction: 'down', detail: '3.5% — near record low' },
            { name: 'VIX', direction: 'up', detail: 'Elevated 25-35 range' },
        ],
        sentiment: 'Classic gold bear case: rapidly rising real yields increased the opportunity cost of holding gold, while dollar strength at 20-year highs made gold expensive globally. Despite 40-year-high inflation, real rates dominated.',
        keyDrivers: 'Fed tightening, soaring real rates, 20-year dollar high',
    },
    {
        id: 'central-bank-buying',
        date: '2023-10-27',
        title: 'Central Bank Buying Frenzy',
        direction: 'bullish',
        priceFrom: 1820,
        priceTo: 2063,
        change: '+13.4%',
        summary: 'Record central bank gold purchases (1,037 tonnes in 2023) drove gold higher despite elevated real rates. Geopolitical de-dollarization narrative gained traction.',
        factors: [
            { name: 'Real Rates', direction: 'up', detail: 'Still elevated ~2%' },
            { name: 'DXY', direction: 'flat', detail: 'Rangebound 103-107' },
            { name: 'VIX', direction: 'down', detail: 'Relatively calm' },
            { name: 'CPI', direction: 'down', detail: 'Inflation declining to ~3%' },
        ],
        sentiment: 'A paradigm shift in gold price drivers. Traditional correlations (real rates, DXY) partially broke down as central banks — especially China, Poland, India — became the dominant marginal buyer. Geopolitical fragmentation and de-dollarization.',
        keyDrivers: 'Record CB buying, de-dollarization, geopolitical hedging',
    },
    {
        id: 'gold-3000',
        date: '2025-02-14',
        title: 'Gold Breaks $3,000',
        direction: 'bullish',
        priceFrom: 2650,
        priceTo: 3100,
        change: '+17.0%',
        summary: 'Gold shattered the $3,000 barrier as continued central bank accumulation, geopolitical tensions, fiscal deficit concerns, and AI-driven economic uncertainty fueled the rally.',
        factors: [
            { name: 'Real Rates', direction: 'down', detail: 'Declining on cut expectations' },
            { name: 'DXY', direction: 'down', detail: 'Weakening dollar' },
            { name: 'CPI', direction: 'flat', detail: 'Sticky around 3%' },
            { name: 'VIX', direction: 'up', detail: 'Rising uncertainty' },
            { name: 'Unemployment', direction: 'up', detail: 'Gradually rising' },
        ],
        sentiment: 'The $3,000 milestone represented a structural shift in gold\'s role. Persistent central bank buying, US fiscal concerns ($35T+ debt), geopolitical fragmentation, and the breakdown of traditional financial correlations propelled gold into a new regime.',
        keyDrivers: 'Central bank demand, fiscal concerns, geopolitical fragmentation, weakening dollar',
    },
    {
        id: 'tariff-escalation-2025',
        date: '2025-04-02',
        title: 'Liberation Day Tariffs — Trade War Escalation',
        direction: 'bullish',
        priceFrom: 3050,
        priceTo: 3200,
        change: '+4.9%',
        summary: 'Trump\'s "Liberation Day" tariff package imposed sweeping reciprocal tariffs on nearly all US trading partners. Markets tumbled on stagflation fears while gold surged as the ultimate safe haven amid global trade disruption.',
        factors: [
            { name: 'VIX', direction: 'up', detail: 'Spiked above 40 on trade war fears' },
            { name: 'DXY', direction: 'down', detail: 'Dollar weakened on growth concerns' },
            { name: 'CPI', direction: 'up', detail: 'Tariff-driven inflation expectations surging' },
            { name: 'Real Rates', direction: 'down', detail: 'Recession fears crushing yields' },
            { name: 'Unemployment', direction: 'up', detail: 'Labor market softening' },
        ],
        sentiment: 'The most aggressive US tariff action since Smoot-Hawley triggered a global flight to safety. Stagflation fears — rising prices with slowing growth — created a perfect bid for gold as both an inflation hedge and safe haven simultaneously.',
        keyDrivers: 'Trade war escalation, stagflation fears, dollar weakness, VIX spike',
    },
    {
        id: 'gold-correction-2025',
        date: '2025-06-15',
        title: 'Trade Deal Hopes — Gold Pulls Back',
        direction: 'bearish',
        priceFrom: 3250,
        priceTo: 3050,
        change: '-6.2%',
        summary: 'Temporary gold correction as US-China trade negotiations showed progress and risk appetite returned. Dollar strengthened briefly on deal optimism.',
        factors: [
            { name: 'VIX', direction: 'down', detail: 'Declining on deal optimism' },
            { name: 'DXY', direction: 'up', detail: 'Dollar bounced on positive sentiment' },
            { name: 'Real Rates', direction: 'up', detail: 'Yields rising on growth hopes' },
            { name: 'CPI', direction: 'flat', detail: 'Inflation expectations moderating' },
        ],
        sentiment: 'Classic risk-on rotation: trade deal hopes pulled capital from safe havens back into equities. However, the pullback was shallow compared to prior corrections, suggesting structural demand from central banks provided a floor.',
        keyDrivers: 'Trade deal optimism, risk-on rotation, dollar bounce',
    },
    {
        id: 'fiscal-crisis-2025',
        date: '2025-10-08',
        title: 'US Fiscal Concerns — Debt Ceiling Crisis',
        direction: 'bullish',
        priceFrom: 3100,
        priceTo: 3350,
        change: '+8.1%',
        summary: 'A prolonged US debt ceiling standoff combined with a Fitch rating review rattled bond markets. Gold surged as confidence in US fiscal management deteriorated and central banks accelerated diversification away from Treasuries.',
        factors: [
            { name: 'VIX', direction: 'up', detail: 'Spiked on default fears' },
            { name: 'DXY', direction: 'down', detail: 'Dollar sold on fiscal uncertainty' },
            { name: 'Real Rates', direction: 'down', detail: 'Flight to safety compressed yields' },
            { name: 'Unemployment', direction: 'up', detail: 'Rising toward 4.5%' },
            { name: 'CPI', direction: 'up', detail: 'Tariff passthrough keeping inflation sticky' },
        ],
        sentiment: 'The fiscal credibility of the United States came under direct question. With $36T+ in debt and no resolution in sight, foreign central banks accelerated gold accumulation as a reserve alternative to Treasuries. A structural shift in global reserve allocation.',
        keyDrivers: 'Debt ceiling crisis, fiscal credibility erosion, CB reserve diversification',
    },
    {
        id: 'gold-3500-2026',
        date: '2026-02-20',
        title: 'Gold Approaches $3,500',
        direction: 'bullish',
        priceFrom: 3350,
        priceTo: 3520,
        change: '+5.1%',
        summary: 'Gold pushed toward $3,500 as the structural bull market continued. Ongoing trade tensions, persistent central bank buying, weakening dollar, and geopolitical fragmentation sustained demand.',
        factors: [
            { name: 'Real Rates', direction: 'down', detail: 'Fed cutting as economy slows' },
            { name: 'DXY', direction: 'down', detail: 'Dollar in sustained downtrend' },
            { name: 'CPI', direction: 'flat', detail: 'Inflation sticky at 3-3.5%' },
            { name: 'VIX', direction: 'up', detail: 'Elevated on geopolitical risks' },
            { name: 'Unemployment', direction: 'up', detail: 'Approaching 5%' },
        ],
        sentiment: 'Gold entered a new price regime driven by structural forces: de-dollarization, fiscal concerns, geopolitical fragmentation, and central bank reserve diversification. Traditional correlations with real rates continued to break down as sovereign buyers dominated.',
        keyDrivers: 'Structural CB demand, de-dollarization, Fed cuts, fiscal deterioration',
    },
];


// --- Presidential Terms (Enhanced) ---
const PRESIDENTIAL_TERMS = [
    {
        name: 'Bill Clinton',
        term: '1993 – 2001',
        party: 'democrat',
        goldStart: 330,
        goldEnd: 272,
        change: '-17.6%',
        high: 415,
        low: 253,
        context: 'Strong dollar policy, tech boom, budget surpluses — worst environment for gold.',
        keyEvents: [
            { year: '1993-96', event: 'Strong dollar policy under Rubin', impact: 'bearish' },
            { year: '1997-98', event: 'Asian Financial Crisis & LTCM', impact: 'neutral' },
            { year: '1999', event: 'UK sells 50% of gold reserves (Brown\'s Bottom)', impact: 'bearish' },
            { year: '2000', event: 'Dot-com bubble peaks then crashes', impact: 'neutral' },
        ],
        macroSnapshot: {
            fedFunds: '3.0% → 6.5%',
            inflation: '2.7% → 3.4%',
            dxy: '97 → 119',
            unemployment: '7.3% → 4.2%',
            debt: '$4.4T → $5.7T',
        },
        analysis: 'The worst era for gold in modern history. A booming economy, strong dollar, budget surpluses, and central bank gold sales created persistent headwinds. The tech bubble absorbed all speculative capital. Gold was widely considered a "barbarous relic" with no future.',
    },
    {
        name: 'George W. Bush',
        term: '2001 – 2009',
        party: 'republican',
        goldStart: 272,
        goldEnd: 882,
        change: '+224.3%',
        high: 1011,
        low: 256,
        context: '9/11, Iraq War, weak dollar, GFC — multiple crises drove sustained gold bull market.',
        keyEvents: [
            { year: '2001', event: '9/11 terrorist attacks — emergency rate cuts to 1%', impact: 'bullish' },
            { year: '2003', event: 'Iraq War — geopolitical premium, twin deficits expand', impact: 'bullish' },
            { year: '2007', event: 'Subprime mortgage crisis begins', impact: 'bullish' },
            { year: '2008', event: 'Lehman collapse — GFC — Bear Stearns, AIG, QE1', impact: 'bullish' },
        ],
        macroSnapshot: {
            fedFunds: '6.5% → 0.25%',
            inflation: '3.4% → -0.4%',
            dxy: '119 → 83',
            unemployment: '4.2% → 7.8%',
            debt: '$5.7T → $10.6T',
        },
        analysis: 'The defining gold bull market of the 21st century began here. A cascade of crises — 9/11, Afghanistan, Iraq, and the GFC — forced rates from 6.5% to zero and the dollar from 119 to 83. Federal debt nearly doubled. Every macro factor structurally favored gold.',
    },
    {
        name: 'Barack Obama',
        term: '2009 – 2017',
        party: 'democrat',
        goldStart: 882,
        goldEnd: 1151,
        change: '+30.5%',
        high: 1921,
        low: 1049,
        context: 'QE-driven peak to $1,921 in 2011, then taper tantrum crash. Net positive but volatile.',
        keyEvents: [
            { year: '2009-10', event: 'QE1 ($1.75T) & QE2 ($600B) — massive monetary expansion', impact: 'bullish' },
            { year: '2011', event: 'US credit downgrade + EU debt crisis → gold ATH $1,921', impact: 'bullish' },
            { year: '2013', event: 'Bernanke taper tantrum — gold crashes 28%', impact: 'bearish' },
            { year: '2015-16', event: 'First Fed rate hike in decade, gold bottoms at $1,049', impact: 'bearish' },
        ],
        macroSnapshot: {
            fedFunds: '0.25% → 0.75%',
            inflation: '-0.4% → 2.1%',
            dxy: '83 → 103',
            unemployment: '7.8% → 4.7%',
            debt: '$10.6T → $19.9T',
        },
        analysis: 'A tale of two halves. The first half (2009-2012) was the peak of the post-GFC gold bull run, driven by QE and negative real rates, culminating in the $1,921 all-time high. The second half (2013-2016) saw the taper tantrum wipe out years of gains as real rates normalized and the dollar strengthened.',
    },
    {
        name: 'Donald Trump (1st)',
        term: '2017 – 2021',
        party: 'republican',
        goldStart: 1151,
        goldEnd: 1898,
        change: '+64.9%',
        high: 2075,
        low: 1124,
        context: 'Trade wars, COVID pandemic, unlimited QE, zero rates — gold hit new ATH at $2,075.',
        keyEvents: [
            { year: '2017', event: 'Tax Cuts & Jobs Act — initial reflation trade hurt gold', impact: 'bearish' },
            { year: '2018-19', event: 'US-China trade war escalation — tariffs on $360B', impact: 'bullish' },
            { year: 'Mar 2020', event: 'COVID crash — liquidity crisis then unlimited QE', impact: 'bullish' },
            { year: 'Aug 2020', event: 'New ATH $2,075 — record negative real rates (-1.08%)', impact: 'bullish' },
        ],
        macroSnapshot: {
            fedFunds: '0.75% → 0.25%',
            inflation: '2.1% → 1.4%',
            dxy: '103 → 90',
            unemployment: '4.7% → 6.7%',
            debt: '$19.9T → $27.8T',
        },
        analysis: 'Initially negative for gold (tax cuts drove dollar strength and reflation trade), the term pivoted dramatically. The US-China trade war provided a structural bid, then COVID triggered the most extreme monetary response in history — unlimited QE, zero rates, and $5T in fiscal stimulus. Gold broke to a new all-time high of $2,075.',
    },
    {
        name: 'Joe Biden',
        term: '2021 – 2025',
        party: 'democrat',
        goldStart: 1898,
        goldEnd: 2650,
        change: '+39.6%',
        high: 2790,
        low: 1622,
        context: 'Inflation spike, Fed hiking, then central bank buying frenzy. Gold resilient despite high rates.',
        keyEvents: [
            { year: '2021-22', event: 'Inflation surges to 9.1% — 40-year high', impact: 'mixed' },
            { year: '2022', event: 'Fed hikes 425bps — most aggressive cycle in 40 years', impact: 'bearish' },
            { year: '2023', event: 'Central banks buy 1,037 tonnes — record year', impact: 'bullish' },
            { year: '2024', event: 'Gold rallies +28% despite high real rates — paradigm shift', impact: 'bullish' },
        ],
        macroSnapshot: {
            fedFunds: '0.25% → 4.50%',
            inflation: '1.4% → 3.0%',
            dxy: '90 → 104',
            unemployment: '6.7% → 4.1%',
            debt: '$27.8T → $36.2T',
        },
        analysis: 'A paradox for gold. The worst inflation in 40 years should have been bullish, but the Fed\'s aggressive response (525bps of hikes) sent real rates soaring and the dollar to 20-year highs. Yet gold held up remarkably well thanks to a structural shift: record central bank buying as geopolitical fragmentation accelerated de-dollarization. By 2024, traditional correlations were breaking down.',
    },
    {
        name: 'Donald Trump (2nd)',
        term: '2025 – Present',
        party: 'republican',
        goldStart: 2650,
        goldEnd: 3520,
        change: '+32.8%',
        high: 3540,
        low: 2596,
        context: 'Liberation Day tariffs, trade wars, debt ceiling crisis, fiscal deterioration — gold surged past $3,500 on structural demand.',
        keyEvents: [
            { year: 'Feb 2025', event: 'Gold breaks $3,000 on tariff fears & CB buying', impact: 'bullish' },
            { year: 'Apr 2025', event: 'Liberation Day — sweeping reciprocal tariffs on all partners', impact: 'bullish' },
            { year: 'Oct 2025', event: 'Debt ceiling crisis — Fitch review, bond market turmoil', impact: 'bullish' },
            { year: 'Feb 2026', event: 'Gold approaches $3,500 — structural bull market', impact: 'bullish' },
        ],
        macroSnapshot: {
            fedFunds: '4.50% → 3.75%',
            inflation: '3.0% → 3.4%',
            dxy: '104 → 98',
            unemployment: '4.1% → 4.8%',
            debt: '$36.2T → $38T+',
        },
        analysis: 'The most bullish presidential term for gold since George W. Bush. Sweeping tariff policies triggered stagflation fears, the dollar weakened sharply, and a debt ceiling crisis eroded US fiscal credibility. Central banks continued record gold accumulation as de-dollarization accelerated. The Fed was forced to cut rates despite sticky inflation — a goldilocks setup for gold.',
    },
];
